language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t sppapalkar/react-app -f Dockerfile.dev .

script:
    docker run -e CI=true sppapalkar/react-app npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react-docker"
    env: "ReactDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-600216437660"
    bucket_path: "react-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"