language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t sppapalkar/react-app -f Dockerfile.dev .

script:
    docker run sppapalkar/react-app CI=true npm run test -- --coverage