language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t sppapalkar/react-app -f Dockerfile.dev .

script:
    docker run -e CI=true sppapalkar/react-app npm run test -- --coverage